
FROM node:19.6-alpine AS build

WORKDIR /usr/src/app

COPY package*.json ./

RUN --mount=type=cache,target=/usr/src/app/.npm \
  npm set cache /usr/src/app/.npm && \
  npm ci


COPY . .

RUN npm run build


FROM nginx:alpine

ENV NODE_ENV=production


COPY --from=build /usr/src/app/build /usr/share/nginx/html


EXPOSE 80


